spring:
  datasource:
    url: jdbc:mysql://camping-app-backend-database.cjorih4jsles.ap-northeast-2.rds.amazonaws.com:3306/camping
    username: root
    password: ehdgml1!2
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        default_batch_fetch_size: 100
  logging:
    level:
      org.hibernate.SQL: debug
      # org.hibernate.type: trace
