spring:
  datasource:
    url: jdbc:mysql://camping-app-backend-database.cjorih4jsles.ap-northeast-2.rds.amazonaws.com:3306/camping?useSSL=false&serverTimezone=UTC
    username: root
    password: ehdgml1!2
  hikari:
    connectionTimeout: 30000
    maximumPoolSize: 5
    minimumIdle: 2
    idleTimeout: 600000
    poolName: SpringBootMySQL
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
